version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/math"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/core"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/spec"
    schedule:
      interval: "weekly"
